services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_USER: reservImmo
      POSTGRES_PASSWORD: reservImmo
      POSTGRES_DB: reservImmo_db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
